name: Release

on:
  push:
    tags:
    - '*'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.s6_arch }}
    steps:
      - uses: actions/checkout@v2
      - id: matrix
        run: |
          echo '::set-output name=s6_arch::'$(cut -f1 conf/toolchains | sed -z '$ s/\n$//' | jq -R -s -c 'split("\n")')

      - uses: ncipollo/release-action@v1
        with:
          omitBodyDuringUpdate: true
          allowUpdates: true

  release:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        s6_arch: ${{fromJson(needs.setup.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v2

      # normalize version (remove 'git/refs/', remove leading 'v')
      - run: |
          VERSION="${GITHUB_REF##*/}"
          VERSION="${VERSION#v}"
          echo "::-set-env name=VERSION::${VERSION}"

      # create short arch name (SARCH)
      - run:
          SARCH=$(cut -f1 -d'-' "${{ matrix.s6_arch }}")
          if "${{matrix.s6_arch}}" = "arm-linux-musleabihf" ; then
            SARCH="armhf"
          fi
          echo "::-set-env NAME=SARCH::${SARCH}"

      - run: |
          make ARCH="${{ matrix.s6_arch }}" VERSION="${VERSION}"

      # by default, arm-linux-musleabi and arm-linux-musleabihf produce tarballs named "arm",
      # move arm-linux-musleabihf to "armhf" to distinguish
      - run: |
          cd output ; for f in s6-overlay-arm* ; do mv "$f" "s6-overlay-armhf${f#s6-overlay-arm}" ; done
        if: ${{ matrix.s6_arch == 'arm-linux-musleabihf' }}

      - run: |
          cd output ; for f in *.tar* ; do sha256sum "$f" > "$f".sha256 ; done

      # output arch-specific binary
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "output/s6-overlay-${{env.SARCH}}*"
          omitBodyDuringUpdate: true
          allowUpdates: true

      - run: |
          rm output/s6-overlay-${SARCH}*

      # upload symlinks/non-arch on x86_64 only
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "output/*.tar.*;output/*.sha256"
          omitBodyDuringUpdate: true
          allowUpdates: true
        if: ${{ matrix.s6_arch == 'x86_64-linux-musl' }}
